title: Батискаф FuntooMacs
description: Бортжурнал погружений в Funtoo, Emacs и другие субстанции
url: http://visconte.github.com
imgdir: http://dl.dropbox.com/u/35307988/visconte.github.com/images
markdown: kramdown
pygments: yes
exclude: ['.bundle', 'draft', 'others', 'temp', 'vendor', 'Gemfile', 'Gemfile.lock']
