handlers:
- url: '/'
  static_files: '_site/index.html'
  upload: '_site/.*'

- url: '/(.*?)/(.*)'
  static_files: '_site/\1/\2'
  upload: '_site/(.*?)/(.*)'

- url: '/(.*?)/(.*?)/(.*?)/(.*)'
  static_files: '/_site/\1/\2/\3/\4'
  upload: '_site/(.*?)/(.*?)/(.*?)/(.*)'